# Generated by Django 2.1.15 on 2023-04-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(default=1234567890, max_length=20),
            preserve_default=False,
        ),
    ]
