# Generated by Django 2.1.15 on 2023-04-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_ticket_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(default='10504 Princess Elizabeth Ave NW building w, Edmonton, AB T5G 3K4', max_length=255),
            preserve_default=False,
        ),
    ]
