# Generated by Django 2.1.15 on 2023-04-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_ticket_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
