# Generated by Django 2.1.15 on 2023-04-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_auto_20230418_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='performance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
